language: minimal
dist: xenial

env:
  global:
    - COMPOSE_FILE=docker-stack.yml

matrix:
  include:
    - name: tests
      env: 
        - BUILD_SCRIPT_PATH=./scripts/build_dev.sh
        - COVERAGE=true
    - name: edge
      env: 
        - BUILD_SCRIPT_PATH=./scripts/build_edge.sh
        - COVERAGE=false
  allow_failures:
    - name: edge

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker-compose --version

install: 
  - chmod +x ${BUILD_SCRIPT_PATH}
  - bash ${BUILD_SCRIPT_PATH}
  - docker-compose up -d
  - docker-compose ps

script:
  - docker-compose exec nereid-tests pytest -v
  - docker-compose exec nereid-tests mypy -p nereid

after_success:
  - if [ ${COVERAGE} = true ]; then
      docker-compose exec nereid-tests coverage run -m pytest;
      docker-compose exec nereid-tests coverage report -m;
      docker-compose exec nereid-tests coverage xml;
      docker-compose exec nereid-tests cat /nereid/coverage.xml > coverage.xml;
      docker-compose exec nereid-tests cat /nereid/.coverage > .coverage;
      bash <(curl -s https://codecov.io/bash);
    fi