before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker-compose --version
  - chmod +x /scripts/build_dev.sh
  - ./scripts/build_dev.sh
  - docker-compose -f docker-stack.yml up -d
  - docker-compose -f docker-stack.yml ps
  - docker-compose -f docker-stack.yml exec nereid-tests bash /run-tests.sh


