version: '3.7'
services:
  nereid:
    volumes:
      - ${PROJECT_DATA_DIRECTORY:-./_project_data}:/nereid/nereid/data/project_data
  celeryworker:
    volumes:
      - ${PROJECT_DATA_DIRECTORY:-./_project_data}:/nereid/nereid/data/project_data
  nereid-tests:
    volumes:
      - ${PROJECT_DATA_DIRECTORY:-./_project_data}:/nereid/nereid/data/project_data