version: '3.7'
services:
  celeryworker:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: celeryworker-edge
  nereid-tests:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: nereid-edge-tests
  redis:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: redis
  nereid:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: nereid
