services:
  nereid:
    build:
      context: .
      target: nereid

  celeryworker:
    build:
      context: .
      target: celeryworker-edge

  nereid-tests:
    build:
      context: .
      target: nereid-edge-tests

  redis:
    build:
      context: .
      target: redis

  flower:
    build:
      context: .
      target: flower
