version: '3.4'
services:
  nereid:
    env_file:
      - env.env
  nereid-tests:
    env_file:
      - env.env
  celeryworker:
    env_file:
      - env.env
    environment:
      - RUN=celery worker --app nereid.bg_worker -l info -c 1
