version: '3.7'
services:
  nereid:
    command: /start-reload.sh
    volumes:
      - ./nereid/nereid:/nereid/nereid
      - ${PROJECT_DATA_DIRECTORY:-./_project_data}:/nereid/nereid/data/project_data:ro
    ports:
      - published: 8080
        target: 80

  celeryworker:
    volumes:
      - ./nereid/nereid:/nereid/nereid
      - ${PROJECT_DATA_DIRECTORY:-./_project_data}:/nereid/nereid/data/project_data:ro

  nereid-tests:
    volumes:
      - ./nereid/nereid:/nereid/nereid
      - ${PROJECT_DATA_DIRECTORY:-./_project_data}:/nereid/nereid/data/project_data:ro
