services:
  celeryworker:
    build:
      context: C:\Users\aorr\Dropbox\Python\sources\nereid-geosyntec\nereid\nereid
      dockerfile: Dockerfile.celeryworker
    depends_on:
    - redis
    environment:
      CELERY_BROKER_URL: redis://guest@redis:6379/0
      CELERY_RESULT_BACKEND: redis://guest@redis:6379/0
      RUN: celery worker --app nereid.bg_worker -l info -c 1
  nereid:
    build:
      context: C:\Users\aorr\Dropbox\Python\sources\nereid-geosyntec\nereid\nereid
      dockerfile: Dockerfile.nereid
    environment:
      CELERY_BROKER_URL: redis://guest@redis:6379/0
      CELERY_RESULT_BACKEND: redis://guest@redis:6379/0
    ports:
    - published: 80
      target: 80
    - published: 8888
      target: 8888
  nereid-tests:
    build:
      context: C:\Users\aorr\Dropbox\Python\sources\nereid-geosyntec\nereid\nereid
      dockerfile: Dockerfile.tests
  redis:
    build:
      context: C:\Users\aorr\Dropbox\Python\sources\nereid-geosyntec\nereid\nereid
      dockerfile: Dockerfile.redis
    image: redis:5.0.6-alpine
    ports:
    - published: 6379
      target: 6379
version: '3.3'

