version: '3.4'
services:
  
  nereid:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      image: sitkacontainers.azurecr.io/ocstormwatertools/nereid_nereid
      target: nereid
  
  celeryworker:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      image: sitkacontainers.azurecr.io/ocstormwatertools/nereid_celeryworker
      target: celeryworker

  nereid-tests:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      image: sitkacontainers.azurecr.io/ocstormwatertools/nereid_nereid-tests
      target: nereid-tests

  redis:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      image: sitkacontainers.azurecr.io/ocstormwatertools/nereid_redis
      target: redis
