version: '3.7'
services:
  nereid:
    environment:
      - NEREID_ASYNC_MODE=replace
    env_file:
      - env.env
  nereid-tests:
    env_file:
      - env.env
  celeryworker:
    env_file:
      - env.env
  flower:
    env_file:
      - env.env
