version: "3.7"
services:
  nereid:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: nereid
    env_file:
      - env.env
    ports:
      - 80:80

  celeryworker:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: celeryworker
    env_file:
      - env.env

  nereid-tests:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: nereid-tests
    env_file:
      - env.env

  redis:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: redis

  flower:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: flower
    env_file:
      - env.env
    ports:
      - 5555:5555
