version: '3.4'
services:
  
  nereid:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: sitkacontainers.azurecr.io/ocstormwatertools/nereid_nereid
  
  celeryworker:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: sitkacontainers.azurecr.io/ocstormwatertools/nereid_celeryworker

  nereid-tests:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: sitkacontainers.azurecr.io/ocstormwatertools/nereid_nereid-tests

  redis:
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: sitkacontainers.azurecr.io/ocstormwatertools/nereid_redis
