version: '3.7'
services:
  nereid:
    volumes:
      - ./nereid/nereid:/nereid/nereid
  celeryworker:
    volumes:
      - ./nereid/nereid:/nereid/nereid
  nereid-tests:
    volumes:
      - ./nereid/nereid:/nereid/nereid