version: '3.4'
services:
  
  nereid:
    image: sitkacontainers.azurecr.io/ocstormwatertools/nereid_nereid
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: nereid
  
  celeryworker:
    image: sitkacontainers.azurecr.io/ocstormwatertools/nereid_celeryworker
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: celeryworker

  nereid-tests:
    image: sitkacontainers.azurecr.io/ocstormwatertools/nereid_nereid-tests
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: nereid-tests

  redis:
    image: sitkacontainers.azurecr.io/ocstormwatertools/nereid_redis
    build:
      context: ./nereid
      dockerfile: Dockerfile.multi
      target: redis
