FROM python:3.7

RUN apt-get update \
  && apt-get install -y --no-install-recommends graphviz \
  && rm -rf /var/lib/apt/lists/*

COPY ./nereid /nereid/nereid
ENV PYTHONPATH=/nereid
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
WORKDIR /nereid

ENV C_FORCE_ROOT=1

COPY ./scripts/run-worker.sh /run-worker.sh
RUN chmod +x /run-worker.sh

CMD ["bash", "/run-worker.sh"]