name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Azure
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: build stack
        env:
          ACR_SERVER: ${{ secrets.ACR_SERVER }}
        run: |
          docker --version
          bash ./scripts/build_deploy.sh
          docker-compose -f docker-stack.yml build
          docker-compose -f docker-stack.yml push
