name: Lint

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Linters
        run: |
          pip install \
            -r requirements/requirements_nereid.txt \
            -r requirements/requirements_lint.txt
      - name: Run Linters
        run: bash scripts/lint.sh
