name: Lint & Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches:
      - develop
      - master
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  python-test:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get install graphviz
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Linters
        run: pip install -r nereid/requirements.txt -r nereid/requirements_tests.txt
      - name: Run Linters
        continue-on-error: true
        run: bash scripts/lint.sh
      - name: Run Tests
        run: |
          coverage run --source=nereid/nereid/src --branch -m pytest nereid/nereid/tests/test_src -xv
          coverage report -m --omit=*test*

  python-edge-test:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get install graphviz
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Deps
        run: |
          pip install --upgrade pip
          awk -F"==" '{print $1}' nereid/requirements.txt nereid/requirements_tests.txt > nereid/requirements_edge.txt
          pip install -r nereid/requirements_edge.txt
      - name: Run Edge Linters
        continue-on-error: true
        run: bash scripts/lint.sh
      - name: Run Edge Tests
        run: |
          pytest nereid/nereid/tests/test_src -xv

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-stack.yml

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build stack
        run: |
          docker --version
          bash ./scripts/build_deploy.sh
          docker-compose up -d nereid-tests

      - name: run tests
        run: docker-compose exec -T nereid-tests coverage run -m pytest -xv

      - name: coverage
        run: |
          docker-compose exec -T nereid-tests coverage report -mi
          docker-compose exec -T nereid-tests coverage xml
          docker-compose exec -T nereid-tests cat /nereid/coverage.xml > coverage.xml
          docker-compose exec -T nereid-tests cat /nereid/.coverage > .coverage

      - name: upload coverage
        uses: codecov/codecov-action@v1

  test-edge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-stack.yml

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build stack
        run: |
          docker --version
          bash ./scripts/build_edge.sh
          docker-compose up -d nereid-tests

      - name: run edge tests
        run: docker-compose exec -T nereid-tests pytest -xv
