name: Test

on:
  push:
    branches:
      - develop
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    # twice per month
    - cron: "0 10 1,15 * *"

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y graphviz
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Deps
        run: pip install -r nereid/requirements.txt -r nereid/requirements_tests.txt
      - name: Run Tests
        run: |
          coverage run --source=nereid/nereid/src --branch -m pytest nereid/nereid/tests/test_src -xv
          coverage report -m --omit=*test*

  python-test-install:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install graphviz
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install nereid as library
        run: |
          pip install .
          pip install pytest
      - name: Run Tests
        run: pytest nereid/nereid/tests/test_src -xv

  python-edge-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
      - run: sudo apt-get install graphviz
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Edge Deps
        run: |
          pip install --upgrade pip
          awk -F"==" '{print $1}' nereid/requirements.txt nereid/requirements_tests.txt > nereid/requirements_edge.txt
          pip install -r nereid/requirements_edge.txt
      - name: Run Edge Tests
        continue-on-error: true
        run: |
          pytest nereid/nereid/tests -xv
      - name: Exit
        run: exit 0

  test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-stack.yml
    steps:
      - uses: actions/checkout@v2
      - name: build stack
        run: |
          docker --version
          bash ./scripts/build_dev.sh
          docker-compose up -d nereid-tests
      - name: run tests
        run: |
          docker compose exec -T nereid-tests coverage run --branch -m pytest nereid/tests -xs
          docker compose exec -T nereid-tests coverage run -a --branch -m pytest nereid/tests/test_api -xs --async
      - name: coverage
        run: |
          docker-compose exec -T nereid-tests coverage report -mi
          docker-compose exec -T nereid-tests coverage xml
          docker-compose exec -T nereid-tests cat /nereid/coverage.xml > coverage.xml
          docker-compose exec -T nereid-tests cat /nereid/.coverage > .coverage
      - name: upload coverage
        uses: codecov/codecov-action@v1

  test-edge:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-stack.yml
    steps:
      - uses: actions/checkout@v2
      - name: build stack
        run: |
          docker --version
          bash ./scripts/build_edge.sh
          docker-compose up -d nereid-tests
      - name: run edge tests
        continue-on-error: true
        run: docker-compose exec -T nereid-tests pytest -xv
      - name: Exit
        run: exit 0
